# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17FDG1afcn4vq1T_sx8FkCcQOXraZX1Jb

Exercise 1:

Create a program that asks the user to enter their name and their age. Print out a message addressed to them that tells them the year that they will turn 100 years old.
"""


name = input("Hello User, I am you're trustworthy computer. Please enter you're name: \n").capitalize()
age = int(input("Would you be so kind to tell me you're age as well? \n")) 

def myfunction(name, age):
    from datetime import date
    current_year = date.today().year
    
    year = current_year + (100 - age)
    altyear = year -1
    
    return name, year, altyear
 

name, year, altyear = myfunction(name, age)
print ("It is nice to meet you,", name, "!\nYou may be surprised, but did you know that you will turn 100 years old in the year", year, "(if you're already celebrated your birthday this year), or in the year", altyear, "if your great day is still to come", end = "?\n\n")
input("If you can't wait to celebrate your 100th birthday in %d (or %d) you should probably spend less time in front of your screen! \n\nSo I recommend to close this program now by pressing Enter." %(year, altyear))